[package]
name = "mundi-net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
futures-util = "0.3.34"
mundi-protocol.workspace = true
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt", "net", "sync", "macros"] }
tokio-tungstenite = "0.30.0"
